name: Update documentation redirects

on:
  push:
    branches: [main]

env:
  FORCE_COLOR: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  update-rtd-redirects:
    runs-on: ubuntu-22.04
    environment: RTD Deploys
    steps:
      - uses: actions/checkout@v4
      - uses: MatteoH2O1999/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install httpx pyyaml rich
      - run: python tools/update-rtd-redirects.py
        env:
          RTD_API_TOKEN: ${{ secrets.RTD_API_TOKEN }}
